version: "3"

services:
  vueapp:
    build: .
    ports:
      - "5000:80"
    restart: always
  
  json-server:
    image: clue/json-server
    restart: always
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "3000:80"